### ISSUE TITLE
How to extend JSON language ?

### ISSUE THREAD

**Issue by vikyd** [Pranomvignesh/extend-monaco-language-tokenizer#1]
JSON language has no `loader` function.

**Comment by Pranomvignesh** [comment]
@vikyd I think you can use semantic tokens provider API from monaco editor
This API is available from version [0.21.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0210-21092020) of monaco editor.
You can tweak [this example from playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example) to make it work for JSON

**Comment by vikyd** [comment]
Only highlight by tokens provider is not enough.

I also want to make it format correctly.

Example, this my input JSON string:

```json
{
  "a": {{myName}}
}
```

I want to highlight `{{myName}}`.

And I also want to format the JSON  string.

Expected:
```json
{
  "a": {{myName}}
}
```

But actually, it become:
```json
{
      "a": {
            {myName
            }
      }
}
```

**Comment by Pranomvignesh** [comment]
@vikyd This package is indented to extend the tokenizer to add custom syntax highlighting only.
And this package will work only if there is a loader method present for the particular language.

For adding custom formatting there are APIs like [registerOnTypeFormattingEditProvider](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerOnTypeFormattingEditProvider), [DocumentRangeFormattingEditProvider](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.DocumentRangeFormattingEditProvider.html)

A little exploration in monaco editor documentation will help you achieve your case
